# fly.toml app configuration file generated for wild-snow-4725 on 2023-04-29T21:19:00-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "linguistiql"
primary_region = "lax"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
