# fly.toml app configuration file generated for linguistiql on 2023-04-30T00:24:30-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "linguistiql"
primary_region = "lax"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
